### PR TITLE
Vite project and typescript

### PR DESCRIPTION
**Pull request by GDur**
I think the project is a cool and valuable resource for ray tracing.
I did not change the algorithm but I modernized the projects tooling and hope it helps others too.

features:
- there is now a package.json
- it is now a vite project (with a dev and build script)
- it uses typescript
- it uses scss
- they wgsl files are now separate which allows for syntax highlighting
- updated the readme accordingly

### CODE REVIEW

**Comment by termuxinator** [comment]
issue with commit
https://github.com/ferminLR/webgpu-path-tracing/pull/3/commits/23df7382c693f4c1de2e00f9dd34325f5725b463

canvas size is hard coded in compute shader
https://github.com/GDur/webgpu-path-tracing/blob/vite-project-and-typescript/src/compute.wgsl

function: compute_main

line: 246
pixel = vec2f(pos)/512.0;

line: 273
let pos_norm = (vec2f(pos)+v2random())/256.0 - 1.0;

maybe solution is put size in uniform

**Comment by termuxinator** [comment]
also we should note that canvas size must be mutiple of 8 because of workgroup

@compute @workgroup_size(8, 8, 1)

and the workgroup dispatch expands from
computePass.dispatchWorkgroups(64, 64, 1);
which is
computePass.dispatchWorkgroups(512/8, 512/8, 1);

so we can do
const workgroupCountX = canvas.width >> 3; // div(8)
const workgroupCountY = canvas.height >> 3;
computePass.dispatchWorkgroups(workgroupCountX, workgroupCountY, 1);

now the canvas size can be any multiple of 8

**Comment by GDur** [comment]
Thank you for looking into it @termuxinator, I tried this and there is still something missing. (still only the bottom left quadrant is drawn)
This was a question I wanted to ask @ferminLR about. Maybe he knows what else has to change. :)

**Comment by termuxinator** [comment]
you have removed canvas size from html
and setAttribute is for css pixels

i did this

const canvas = document.querySelector("canvas")
canvas.width = size.width
canvas.height = size.height

//const pixelRatio = window.devicePixelRatio; // exact pixels
const pixelRatio = 1.0; // scaled pixels

canvas.style.width = canvas.width / pixelRatio + "px";
canvas.style.height = canvas.height / pixelRatio + "px";

along with my other 2 posts above, thats all thats needed to change

**Comment by ferminLR** [comment]
Thanks a lot for your effort @GDur!! And also thanks for your patience, I am really busy lately and haven't been able to check this out before.

I really appreciate the work you have done, but I purposefully wanted to make this project as tiny and lean as possible, without any dependencies. That's why I didn't use vite or webpack or anything similar. And that's also why I didn't use typescript or scss; so you don't even need the ts->js and scss->css transpilers.

Maybe in a future, if the project grows, I will reconsider using more of these changes; but in the meantime I prefer it to stay as close as it is now. One thing I really like though is the ability to change the wgsl code to dedicated files so you can use syntax highlighting; but for those to work you need a properly setup server. Would you consider making a new PR with the minimal changes to just add the vite server and the wgsl files renamed for syntax highlighting, without typescript and scss? I understand if you don't want to do that, considering the effort you already made here.

Thanks for your understanding!

**Comment by ferminLR** [comment]
@GDur regarding the bug you have where only part of the image is shown when changing the canvas size, @termuxinator is right: the size of the render is hardcoded in the compute shader and, for it to be compatible with any resolution, width and height values should be passed to the shader through an uniform.

One easy way to do it would be to extend the `computeUniformsFloat` array to add the canvas width and height, change the `struct Uniforms` in the compute shader accordingly, and use the values in the two lines @termuxinator mentioned.

**Comment by GDur** [comment]
"Thanks a lot for your effort @GDur!! And also thanks for your patience, I am really busy lately and haven't been able to check this out before."

@ferminLR Great to hear back from you and no worries. It was a shot in the dark after all 😄.
And thank you for the nice words and appreciation!

"Would you consider making a new PR with the minimal changes to just add the vite server and the wgsl files renamed for syntax highlighting, without typescript and scss?"


You of course don't have to accept my suggestion, but I would like to make case for the full switch first :)

When using vite, it is necessary to
- use node 
- add a package.json 
- arrange the folder structure as I did

The switch from CSS to SCSS is negligible because it is a superset and the user can still write css inside
The switch from JS to TS comes arguably with a bit more work regarding types but makes up for it by helping devs to get into the code and avoid errors.

The compilers for TS and SCSS are basically not noticeable by the developer and don't influence the resulting file sizes.

So if you like the change to vite and the external files, then the others are just a bonus.

Did you try it? It should just need
> npm i
> npm start

And when saving the files the web page instantly refreshes 

Anyway you decide is OK for me, after all this is your project :)

(And thank you for the canvas-size-bug-hint, I will definitely look into it!)

**Comment by termuxinator** [comment]
i made the changes in a stackblitz project since i dont have a computer.
https://stackblitz.com/~/github.com/termuxinator/webgpu-path-tracing
the only thing i have not done is aspect ratio correction,
so for now the canvas should be square and multiple of 8

**Comment by termuxinator** [comment]
ok, i forked and updated the required changes.
apsect ratio correction has also been added
have fun

**Comment by GDur** [comment]
> i made the changes in a stackblitz project since i dont have a computer. https://stackblitz.com/~/github.com/termuxinator/webgpu-path-tracing the only thing i have not done is aspect ratio correction, so for now the canvas should be square and multiple of 8

> ok, i forked and updated the required changes. apsect ratio correction has also been added have fun

@termuxinator  Very nice! Works great, thank you!

This way, an aspired fullscreen mode should not be far fetched now :)
(just as a fun fact: in the future I would like to try make it realtime by implementing a denoiser, which is probably a lot of effort  and take a while but hey, a man can dream :D)

You can create a pull request for that if you want, otherwise I might do it :)
Either way good stuff :)

**Pull request closed without merging**
